import React, { useState, useEffect } from 'react';
import { alertAPI } from '../utils/api';

const SEV_LABELS = { critical: '🔴 Critical', warning: '🟡 Warning', info: '🔵 Info' };
const TYPE_LABELS = {
  stop_loss:          '🛑 Stop Loss',
  price_drop:         '📉 Price Drop',
  price_surge:        '📈 Price Surge',
  target_reached:     '🎯 Target Reached',
  high_risk:          '⚠️ High Risk',
  low_diversification:'🟡 Low Diversification'
};

const AlertsPage = () => {
  const [alerts, setAlerts]     = useState([]);
  const [unread, setUnread]     = useState(0);
  const [loading, setLoading]   = useState(true);
  const [filter, setFilter]     = useState({ severity: '', isRead: '' });

  const load = async () => {
    setLoading(true);
    try {
      const res = await alertAPI.getAll(filter);
      setAlerts(res.data.alerts);
      setUnread(res.data.unreadCount);
    } catch {}
    setLoading(false);
  };

  useEffect(() => { load(); }, [filter]);

  const markRead = async (id) => {
    await alertAPI.markRead(id);
    load();
  };

  const dismiss = async (id) => {
    await alertAPI.dismiss(id);
    load();
  };

  const readAll = async () => {
    await alertAPI.readAll();
    load();
  };

  return (
    <div style={{ padding: '1.5rem', maxWidth: 900, margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h1 style={{ fontSize: '1.5rem', fontWeight: 700 }}>🔔 Alerts</h1>
          <p style={{ color: 'var(--muted)', fontSize: '0.85rem', marginTop: '0.2rem' }}>
            Auto-generated by the Alert Engine — {unread} unread
          </p>
        </div>
        <button className="btn btn-ghost" onClick={readAll}>Mark All Read</button>
      </div>

      {/* Filters */}
      <div className="card" style={{ marginBottom: '1.5rem', display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
        <div>
          <label style={{ color: 'var(--muted)', fontSize: '0.8rem', display: 'block', marginBottom: '0.3rem' }}>Severity</label>
          <select value={filter.severity} onChange={e => setFilter({ ...filter, severity: e.target.value })}
            style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, padding: '0.5rem', color: 'var(--text)', fontFamily: 'inherit' }}>
            <option value="">All Severities</option>
            <option value="critical">Critical</option>
            <option value="warning">Warning</option>
            <option value="info">Info</option>
          </select>
        </div>
        <div>
          <label style={{ color: 'var(--muted)', fontSize: '0.8rem', display: 'block', marginBottom: '0.3rem' }}>Status</label>
          <select value={filter.isRead} onChange={e => setFilter({ ...filter, isRead: e.target.value })}
            style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, padding: '0.5rem', color: 'var(--text)', fontFamily: 'inherit' }}>
            <option value="">All</option>
            <option value="false">Unread</option>
            <option value="true">Read</option>
          </select>
        </div>
      </div>

      {loading ? <div className="spinner" /> : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
          {alerts.length === 0 ? (
            <div className="card" style={{ textAlign: 'center', color: 'var(--muted)', padding: '3rem' }}>
              No alerts found. Add investments to trigger the alert engine!
            </div>
          ) : alerts.map(alert => (
            <div key={alert._id} className={`card sev-${alert.severity}`} style={{ opacity: alert.isRead ? 0.65 : 1, transition: 'opacity 0.2s' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '1rem' }}>
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '0.4rem', flexWrap: 'wrap' }}>
                    <span className={`badge ${alert.severity === 'critical' ? 'badge-red' : alert.severity === 'warning' ? 'badge-yellow' : 'badge-blue'}`}>
                      {SEV_LABELS[alert.severity]}
                    </span>
                    <span className="badge badge-blue">{TYPE_LABELS[alert.alertType]}</span>
                    {!alert.isRead && <span className="badge badge-green">NEW</span>}
                  </div>
                  <p style={{ fontSize: '0.95rem', lineHeight: 1.5 }}>{alert.message}</p>
                  {alert.investment && (
                    <p style={{ color: 'var(--muted)', fontSize: '0.8rem', marginTop: '0.3rem' }}>
                      Asset: {alert.investment.assetName} ({alert.investment.assetType})
                    </p>
                  )}
                  {alert.triggerValue !== undefined && (
                    <p style={{ color: 'var(--muted)', fontSize: '0.8rem' }}>
                      Threshold: {alert.triggerValue} | Actual: {alert.actualValue}
                    </p>
                  )}
                  <p style={{ color: 'var(--muted)', fontSize: '0.75rem', marginTop: '0.4rem' }}>
                    {new Date(alert.createdAt).toLocaleString()}
                  </p>
                </div>
                <div style={{ display: 'flex', gap: '0.5rem', flexShrink: 0 }}>
                  {!alert.isRead && (
                    <button className="btn btn-ghost" style={{ padding: '0.3rem 0.7rem', fontSize: '0.8rem' }} onClick={() => markRead(alert._id)}>
                      ✓ Read
                    </button>
                  )}
                  <button className="btn btn-danger" style={{ padding: '0.3rem 0.7rem', fontSize: '0.8rem' }} onClick={() => dismiss(alert._id)}>
                    ✕
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default AlertsPage;
